CREATE DATABASE DuLich
GO

USE DuLich
CREATE TABLE NguoiDung
(
	MaNguoiDung INT IDENTITY PRIMARY KEY,
	Email NVARCHAR(100),
	Sdt NVARCHAR(100),
	MatKhau NVARCHAR(100),
	TrangThai INT,
	PhanQuyen INT,
	NoiO NVARCHAR(100),
	GioiTinh INT,
	CCCD NVARCHAR(15),
	Ten NVARCHAR(100)
)
